site_name: My Personal Blog
site_url: https://sundarbishnoi.github.io/
nav:
    - Home: index.md
    - Mkdocs learning: sample.md
    - Site Reliability Engineering: 
        - Python : file1.md

theme: readthedocs

